openapi: 3.0.3
info:
  title: L-Osiris NFC Platform - Public API
  version: 1.0.0
  description: Public API specification for L-Osiris NFC Platform

servers:
  - url: http://localhost:3001/v1
    description: Local development server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API
      operationId: getHealth
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
                  service:
                    type: string
                    example: api

  /viewer/entry/{publicTagId}:
    get:
      summary: Get viewer entry by public tag ID
      description: Retrieves viewer entry information by public tag ID
      operationId: getViewerEntry
      tags:
        - Viewer
      parameters:
        - name: publicTagId
          in: path
          required: true
          description: Public tag ID
          schema:
            type: string
      responses:
        '200':
          description: Viewer entry found
          content:
            application/json:
              schema:
                type: object
                properties:
                  publicTagId:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
        '404':
          description: Entry not found